const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {webcrypto}=require('node:crypto');
const Safety=require('../layout-safety.js'),Core=require('../home-layout-marker-core.js');
const html=fs.readFileSync(require.resolve('../home-layout.html'),'utf8');
const edit=fs.readFileSync(require.resolve('../home-layout-edit.html'),'utf8');
const account={app_id:'app',account_id:'01:app',screen:0,cell_x:0,cell_y:0,line_number:1,status:'loser'};
const ctx={safety_version:Safety.VERSION,canonical_revision:1,layout_revision:1,accounts:[account],retired_app_ids:['old']};
test('正本app集合・座標・LINE番号・revisionを別々に検査する',()=>{const local=[{appId:'app',screen:0,cellX:0,cellY:0,lineNumber:1}];assert.equal(Safety.assertCanonical(ctx,local),ctx);for(const change of [{appId:'other'},{cellX:1},{lineNumber:2}])assert.throws(()=>Safety.assertCanonical(ctx,[{...local[0],...change}]),{code:'E_CANONICAL_MISMATCH'});assert.throws(()=>Safety.assertRevision({...ctx,layout_revision:2},ctx),{code:'E_CANONICAL_REVISION'});assert.throws(()=>Safety.assertRevision({...ctx,canonical_revision:2},ctx),{code:'E_CANONICAL_REVISION'})});
test('説明済み旧realだけを外し、未知LINE・現在real消失はCoreで停止する',()=>{const layout={groups:[{campaign:{id:'a',name:'A'},label:'A',active:[{appId:'app'},{appId:'old'}],winners:[]}]};Safety.excludeRetired(layout,ctx);const plan=Core.planCampaign(layout.groups[0],[account],['app']);assert.deepEqual(plan.placementIds,['app']);assert.deepEqual(layout.groups[0].excludedRetired,['old']);const unknown={...layout.groups[0],active:[{appId:'unknown'}]};assert.throws(()=>Core.planCampaign(unknown,[account],['app']));assert.throws(()=>Core.planCampaign({...unknown,active:[]},[account],['app']))});
test('解析から同期を除去、revisionをpreviewとcommitへ伝達、保存クリックで生成物を消さない',()=>{const analyze=edit.slice(edit.indexOf('async function analyze(){'),edit.indexOf('function insertCopy('));assert.doesNotMatch(analyze,/accounts\/sync/);assert.match(analyze,/LayoutSafety.assertCanonical/);assert.match(analyze,/canonical_revision:context.canonical_revision/);assert.match(edit,/canonical_revision:analysis.context.canonical_revision/);const cleanup=edit.slice(edit.indexOf('async function autoCleanupAfterDownload'),edit.indexOf('async function completeWork'));assert.doesNotMatch(cleanup,/if\(row.kind==='generated'&&row.device===device\)\{deleteIds.push/)});
function initialFixture(){
 const rows=new Map(),events=[],handlers=new Map(),nodes=new Map();let committed=false,failPut=false,loseResponse=false,failCache=false;
 const local=[{appId:'app',lineNumber:1,displayName:'1',screen:0,cellX:0,cellY:0}];let settings={devices:{}};
 const $=id=>{if(!nodes.has(id))nodes.set(id,{value:id==='initialDevice'?'01':'',textContent:'',addEventListener:(event,fn)=>handlers.set(id,fn)});return nodes.get(id)};
 const context={console,crypto:webcrypto,Date,Map,Set,Number,String,JSON,Error,$,loadSettings:()=>structuredClone(settings),saveSettings:s=>{events.push('cache');if(failCache)throw Error('localStorage full');settings=structuredClone(s)},
  showConfirm:async()=>true,extractDefaultLayout:async()=>({layout:local,defaultScreens:[0]}),renderFiles:async()=>{},renderInitialStatus:async()=>{},
  getAll:async()=>[...rows.values()],put:async record=>{events.push('put:'+record.kind);if(failPut)throw Error('IDB full');rows.set(record.id,structuredClone(record))},
  apiCall:async(path,options)=>{events.push(path);if(path.startsWith('/api/layout/canonical-commit'))return {committed,result:{canonical_revision:1}};if(path.startsWith('/api/layout/canonical?'))return {canonical_revision:committed?1:0,positions:[],accounts:[]};if(path.endsWith('/preview'))return {preview_token:'token'};if(path==='/api/layout/accounts/sync'){committed=true;if(loseResponse)throw Error('response lost');return {canonical_revision:1}};throw Error(path)}
 };
 vm.createContext(context);
 const funcs=html.slice(html.indexOf('async function commitCanonicalUpdate('),html.indexOf("$('initialDevice').addEventListener"));
 const handler=html.slice(html.indexOf("$('initialFileInput').addEventListener"),html.indexOf("$('backupFileInput').addEventListener"));
 vm.runInContext(funcs+handler,context);
 const submit=()=>handlers.get('initialFileInput')({target:{files:[{name:'test.novabackup',size:100,type:'application/octet-stream',lastModified:1}],value:'file'}});
 return {context,events,rows,submit,get committed(){return committed},settings:()=>settings,message:()=>$('message').textContent,failPut:v=>{failPut=v},loseResponse:v=>{loseResponse=v},failCache:v=>{failCache=v}};
}
test('初期配置はファイル保存→D1確定→local cache。IDB保存失敗なら同期しない',async()=>{const f=initialFixture();await f.submit();assert.equal(f.committed,true);assert.ok(f.events.indexOf('put:pending-canonical')<f.events.indexOf('/api/layout/accounts/sync'));assert.ok(f.events.indexOf('/api/layout/accounts/sync')<f.events.indexOf('cache'));assert.equal([...f.rows.values()][0].kind,'source');const bad=initialFixture();bad.failPut(true);await bad.submit();assert.equal(bad.committed,false);assert.equal(bad.rows.size,0)});
test('初期配置D1成功後の応答喪失は保存操作IDを照会して復旧し、再更新しない',async()=>{const f=initialFixture();f.loseResponse(true);await f.submit();assert.equal(f.committed,true);assert.equal([...f.rows.values()][0].kind,'pending-canonical');const before=f.events.filter(p=>p==='/api/layout/accounts/sync').length;f.loseResponse(false);await f.context.recoverCanonicalUpdate();assert.equal([...f.rows.values()][0].kind,'source');assert.equal(f.events.filter(p=>p==='/api/layout/accounts/sync').length,before);assert.ok(f.settings().devices['01'].pinnedBaseFile)});
test('D1確定後のlocalStorage保存失敗でもファイル・操作情報を保持して再読込復旧',async()=>{const f=initialFixture();f.failCache(true);await f.submit();assert.equal(f.committed,true);assert.equal([...f.rows.values()][0].kind,'pending-canonical');f.failCache(false);await f.context.recoverCanonicalUpdate();assert.equal([...f.rows.values()][0].kind,'source');assert.equal(f.settings().devices['01'].canonicalRevision,1)});
